### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by LachlanStuart** [imzML/imzML#1]
The last commit in this repository removed most of the files. Was this intentional?

As far as I can tell, the [previous revision](https://github.com/imzML/imzML/blob/f2c8b6ce2affa8d8eef74d4bfe5922c815ff4dff/imagingMS.obo) has the only up-to-date (version 1.1.0) copy of `imagingMS.obo` available online. [ms-imaging.org](https://ms-imaging.org/wp/imzml/controlled-vocabulary/) only seems to have version 0.9.1.

**Comment by AlanRace** [comment]
Hi Lachlan,
The files were removed from master as there was discussion around whether we would host them long term on GitHub, but they remained in the development branch to allow the validator access to them still. 

I'll push the files from development to master and we can keep the latest files here.

Thanks,
Alan

**Comment by AlanRace** [comment]
The master branch now contains the version 1.1.0 files.

**Comment by LachlanStuart** [comment]
Thanks @AlanRace !
